# 베이스 이미지 설정 (현재 devcontainer.json과 동일하게 유지)
FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# 작업 디렉토리 설정
WORKDIR /workspace

# 호스트의 모든 파일을 컨테이너에 복사
COPY . .

# 패키지 설치
RUN npm install

# 서버 실행 (devcontainer에서는 CMD가 작동하지 않음. devcontainer.json에서 실행해야 함)
CMD ["node", "index.js"]
